### ISSUE TITLE
Feat: 비슷한 콘텐츠, 추천 콘텐츠 화면 구현

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/movcha#1]
##  📌 Overview
- 비슷한 콘텐츠, 추천 콘테츠를 노출해주는 화면을 구현합니다.
(두 내용을 한 화면에 보여주기 때문에 추천 콘텐츠로 통일하겠습니다...)

<br />

## ✔️ Todo
- [x] 검색 결과 아이템 클릭 시 추천 콘텐츠 화면 연결
- [ ] 추천 콘텐츠 화면 구현
  - [x] 비슷한 콘텐츠 컬렉션 뷰 구현
  - [ ] 추천 콘텐츠 컬렉션 뷰 구현
  - [x] 각 컬렉션 뷰에 프로토콜 & 셀 연결
- [ ] API 연결
  - [x] 네트워크 통신 로직 분리
  - [x] Similar API 연결
  - [ ] Recommendation API 연결
  - [x] 응답값 데이터 바인딩 → 비슷한 콘텐츠만!

<br />

## 🔗 References
- [iOS ) 하나의 델리게이트(Delegate)에 여러개의 요소 연결?](https://zeddios.tistory.com/169)

<br />

### 한 화면에 2개의 컬렉션 뷰를 만들 때
- 첫 시도 : 하나의 컬렉션 뷰에서 섹션을 나누는 것으로 시도했으나 실패
- 레퍼런스 검색 후 컬렉션 뷰 프로토콜에 여러 개의 컬렉션 뷰를 연결할 수 있다는 것을 알고, 비슷한 콘텐츠와 추천 콘텐츠를 띄울 각각의 컬렉션 뷰 생성
- 각각의 컬렉션 뷰에 delegate, dataSource, register 연결하여 해결
