### ISSUE TITLE
Refactor: NetworkManager 추상화 (Enum 연관값 활용) 

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/movcha#10]
##  📌 Overview
- Enum과 연관값을 활용해 네트워크 요청 모듈을 추상화 합니다.

<br />

## ✔️ Todo
- [x] Search API 로직 NetworkManager 파일로 이동
- [x] NetworkManager 추상화 리팩토링 (Enum 연관값 활용)
- [x] API 호출 로직 수정 적용 - 제네릭

<br />

## 🔗 References
- [잘하는 개발자가 되는 그라데이션 사고법 (추상화 계층과 데이터 흐름 이해하기)](https://velog.io/@teo/gradation-thinking)
- [[iOS] Alamofire를 통해 서버와 통신 해보기 - GET](https://roniruny.tistory.com/141)
- [API Call 함수 Generic으로 휘뚜루마뚜루 쓰기](https://velog.io/@simonyain/API-Call-함수-Generic으로-휘뚜루마뚜루-쓰기)
