### ISSUE TITLE
Refactor: BaseView, BaseCell 작업, View-Controller 분리 

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/movcha#12]
##  📌 Overview
- BaseView, BaseCell 등을 통해 중복 코드를 줄이고 View와 Controller를 분리합니다.

<br />

## ✔️ Todo
- [x] BaseView
- [x] BaseCollectionViewCell (poster)
  - [x] 검색 화면
  - [x] 추천 콘텐츠 화면
- [x] BaseViewController 리팩토링 (필요 시)
- [x] View - Controller 분리 (loadView를 통해 뷰 컨트롤러의 뷰 바꿔주기)\
  - [x] 홈 화면
  - [x] 검색 화면
  - [x] 추천 콘텐츠 화면
  - [x] 박스 오피스 화면 

<br />

회원가입 화면, 인기급상승 화면은 추후 별도 브랜치에서 진행 
- 회원가입: 화면 연결 안 되어 있어서 추후 진행
- 인기급상승: API 오류 해결 후 진행
