### ISSUE TITLE
Feat: 인기급상승 콘텐츠 상세 화면 구현

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/movcha#16]
##  📌 Overview
- 인기급상승 상세 화면을 구현합니다.

<br />

## ✔️ Todo
- [x] 인기 급상승 화면 Base 코드 적용 _→ develop_
- [x] 인기 급상승 상세 화면 Base 코드 적용
- [x] 영화/TV 구분하여 Credits API 연결 _→ develop_
- [x] 응답 데이터 바인딩 _→ develop_
- [x] 세부 디자인 수정, 불필요한 코드 삭제

<br />

## 🔗 References
- [TMDb - Credits API - 영화](https://developer.themoviedb.org/reference/movie-credits)
- [TMDb - Credits API - TV](https://developer.themoviedb.org/reference/tv-series-credits)

<br />

### 🤯😭😱🥲
기껏 브랜치를 만들어두고 develop 브랜치에서 작업하는 대참사 발생 ..
Todo에서 화살표 처리 해둔 것들은 develop 브랜치입니다..
