### ISSUE TITLE
Feat: 추천 콘텐츠 영역 구현, Recommendation API 연결

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/movcha#7]
##  📌 Overview
-  추천 콘텐츠 화면에서 하단 추천 콘텐츠 영역을 구현합니다.

<br />

## ✔️ Todo
- [x] Recommendation API 연결
- [x] 응답 데이터 바인딩
- [x] Similar API 로직 수정
- [x] 영화/드라마 분류 따라서 다른 API 연결 체크
